### PR TITLE
Fix #1043: Export does not honor filtered results in table

### LINKED ISSUE #1043: [Bug]: Export does not honor filtered results in table
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.5

### PowerGrid

4.8.1

### Laravel

10.14.1

### Livewire

2.12.3

### Alpine JS

3.12.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

I have an exchange rates table that holds amounts for two different currencies and I filtered the table by one of them. I exported the results to XLSX and expected that the filters would be honored and the resulting Excel file would only contain entries for that currency, but every entry (for both currencies) was exported.

### To Reproduce...

1. Have an exportable populated powergrid table.
2. Apply a filter to it.
3. Export to Excel XLSX file.

### Extra information

I have done some debugging and pinpointed the issue to this line of code: https://github.com/Power-Components/livewire-powergrid/blob/5faeb879af0d31e1d72bd38083d328791ea53ad3/src/Traits/WithExport.php#L180

If I place the following code before that line I can see that the `$processDataSource` paginator instance contains only the filtered values (this would be expected):
 
dd($processDataSource->get()->getCollection()->toArray());
 

Running https://github.com/Power-Components/livewire-powergrid/blob/5faeb879af0d31e1d72bd38083d328791ea53ad3/src/Traits/WithExport.php#L180, specifically `$processDataSource->prepareDataSource()` yields the following error:
`Typed property PowerComponents\LivewirePowerGrid\PowerGridComponent::$datasource must not be accessed before initialization` (I get this error because I placed the command `dd($this->component->datasource);` at the start of the function in line https://github.com/Power-Components/livewire-powergrid/blob/5faeb879af0d31e1d72bd38083d328791ea53ad3/src/ProcessDataSource.php#L51) but it exposes the issue that the datastore contains no value and hence it is being initialized with a "default query".

This is the query that the Paginator executes: ``"select * from `exchange_rates` where ((`currency` = ?) and (`date` between ? and ?))"`` versus the query that the actual results export executes: ``"select * from `exchange_rates`"``.

Is there a datasource assignment missing to use the one that's coming from the filtered component?

### PR DESCRIPTION
**Pull request by axelitus**
This pull request fixes the bug reported in #1043.

### CODE REVIEW

**Review by d4rkstar — APPROVED** [review]
Hello, i've tested this on a test project and it just works with no issues at all.

@luanfreitasdev  is possible to merge this?

**Comment by luanfreitasdev** [comment]
Hello @d4rkstar . I'm going to test it here. I was waiting for it to come out of the draft. @axelitus . Do you have anything else?

**Comment by d4rkstar** [comment]
@luanfreitasdev i would like to add another small feature on the menu :smile:  :
image

If the grid is filtered, the label should change from "ALL" (TUTTI in my image) to "FILTERED"

Like this:

image

What do you think about?

The patch is almost ready (translations..... :face_with_thermometer: )

**Comment by axelitus** [comment]
Hi there, nothing left to add, left it as draft just for reviewing purposes. I'll check it as ready for review.

**Comment by luanfreitasdev** [comment]
Thank you @axelitus

**Pull request merged**
