### PR TITLE
Total row

### PR DESCRIPTION
**Pull request by shishamchudal**
Added Total Row Sum at the bottom of the table.

PR for issue #178

### CODE REVIEW

**Comment by luanfreitasdev** [comment]
Hi  @shishamchudal 

Thanks for the PR!

I really liked the idea of calculating the total of a column but I think the calculation should take into account all the data in the table and not the current page. As it currently stands in the first review I think that total value doesn't take into account the current page and this can be a little confusing.

Another point I would like to see in PR would be other calculations such as: **total, average and sum**,

```
Column::add()
         ->title('Price')
         ->field('price')
         ->wihtSum($lable = 'Sum', $options = ['top' => true, 'bottom' =>true] )
         ->withAvg($lable = 'Average price', $options = ['top' => true, 'bottom' =>true] )
         ->withCount($lable = 'Items', $options = ['top' => true, 'bottom' =>true] )
```

**Comment by dansysanalyst** [comment]
Hi Shisham, 

Thank you so much for the PR. It is really nice to see the community engaging with PowerGrid!

Just to complement what @luanfreitasdev said, I guess it could be a good idea to filter the collection for numeric values.

The idea is to avoid the Exception in case the user chain this method to a text column, like name column.

IMAGE 2021-12-14 23:16:59

As per what the pagination, I find it somewhat deceiving to show the total in page versus the total data in that column.

For instance, a manager searches for "Name = Paul" and receives two pages. 

In the first page, the column sales says, "Total: 10". Then, he goes to the next page and sees "Total 2". 

It would be best that "Total: 12" is always 12, the sum of all sales.

Page 1:
IMAGE 2021-12-14 23:17:01

Page 2:
IMAGE 2021-12-14 23:28:31




Another point, the name "totalRow" sounds a little confusing. We are not summing items in a row, the method sums the column values. Then, `->withSum()` would be better. It would also allow other methods with a similar concept.
The idea of it passing a label is also interesting.  
It allows better usage and internationalization. For instance:  `->withSum('sales total')`,  `->withSum('items')`


Thank you and all the best!

**Comment by shishamchudal** [comment]
Sure, I will get it fixed ASAP! Thanks for the suggestions.

**Comment by shishamchudal** [comment]
Hey,

I was wondering about how to get the non-paginated data into the column. The problem is that we are getting the paginated data and converting it to the collection then letting the collection handle the Sum, Count, Average for us, because the collection is receiving only paginated data the total is different in two paginated columns.

We still want all the filters and searching to work but if we could get all the data before pagination in the table then it would be very easy to implement. 

I just want to know how to retrieve $data before pagination.

Thank you
Shisham Chudal

**Comment by devsquad-luan-freitas** [comment]
I think a good implementation would be to have this functionality separate in an Action class with the methods taking the column name and action type.  
This method can make the 3 functions for enjoyment.

The resolveModel() method can help retrieve the model class being used (take the class path, but don't execute it if there are no columns by calling withSum().

 In the helper class you created you can create a method to read which columns have the method active and then work on the count.

**Comment by shishamchudal** [comment]
Updates:
1. Changed totalRow name to header and footer in the main table setup
2. In the column added features like:
    Column::add()
             ->title('Price')
             ->field('price')
             ->wihtSum($lable = 'Sum', $options = ['header' => true, 'footer' =>true] )
             ->withAvg($lable = 'Average price', $options = ['header' => true, 'footer' =>true] )
             ->withCount($lable = 'Items', $options = ['hearder' => true, 'footer' =>true] )
3. withSum() and withAvg() only works if the column is numeric.
4. withCount() works for all the tables.

**Comment by luanfreitasdev** [comment]
Some points I noticed in the tests:

You can only add one view type per column. (It would be nice if I could put one Item under another as sometimes I want to show the sum and amount or the sum and average together).

You can remove **hasCount**, **hasAvg** and **hasSum** and use this for example: `@if (isset($column->sum['header']))`

Use dataField instead of field (as it should always have the real column name changing price_BRL to price for example).

```php
$withoutPaginatedData->collect()->sum($column->dataField)
```

The two variables in PowerComponents (**$header and $footer**) are unnecessary as you can scan $columns and verify that at least one contains a header or footer.

In PowerComponents: `$this->withoutPaginatedData = $results->get(); `We can't just do a get() on any occasion, it might be worth wrapping in some clever logic to handle this.

For example:
bool
```php
if ($this->showTotalColumns) {
   $this->withoutPaginatedData = $results->get(); 
}
```

You can do this on line 367 as well to be able to handle Collections.

In Column Class 141, I think we can only use Boolean values, for example:
```php
public function withCount(string $label = 'Count', bool $header = true, bool $footer = true): Column
{
        $this->count['label'] = $label;
        $this->count['header'] = $header;
        $this->count['footer'] = $footer;

        return $this;
 }
```
It would be nice if it comes by default with a custom class on the line, for example `px-3 py-2 whitespace-nowrap dark:text-gray-200 text-sm text-gray-600 text-right space-y-2`

**Add in Table Class**: (PowerComponents\LivewirePowerGrid\Themes\Components)
```
$tdBodyClassTotalColumns
$tdBodyStyleTotalColumns
```

**Update in Tailwind Theme**: (PowerComponents\LivewirePowerGrid\Themes) after line 24
```php
->tdBodyTotalColumns('px-3 py-2 whitespace-nowrap dark:text-gray-200 text-sm text-gray-600 text-right space-y-2')
```

**Update in Bootstrap5 Theme**: (PowerComponents\LivewirePowerGrid\Themes) after line 24
```php
->tdBodyForTotalColumns('xxxxxxxxxxxx')
```

**You can use in views:**
```
 $theme->table->tdBodyClassTotalColumns
$theme->table->tdBodyStyleTotalColumns
```

To have a better layout

image
image

Don't forget to run the  **composer fix** and verify that the tests didn't fail before pushing.

Thanks

**Comment by shishamchudal** [comment]
Updates:

1. Removed unnecessary hasCount, hasSum, hasAvg Variables.
2. Changed 
     $withoutPaginatedData->collect()->sum($column->data) to
     $withoutPaginatedData->collect()->sum($column->dataField).
3. Added Logic to only get non paginated data if either heading or footer row is present.
4. Changed to withCount(string $label = 'Count', bool $header = true, bool $footer = true)
5. Added Custom Classes for Sum, Count and Average.
6. Added feature to get all three sum, counts and average at different lines for same column.

Thanks to @luanfreitasdev, @dansysanalyst & @devsquad-luan-freitas for awsome support and feedback.

✌️ Shisham Chudal

**Comment by luanfreitasdev** [comment]
Hi @shishamchudal , Can you check the CI?.

**Comment by shishamchudal** [comment]
Hey @luanfreitasdev, Really very sorry but I can't figure it out. Would you mind helping me out here?

Thanks
Shisham Chudal

**Comment by luanfreitasdev** [comment]
Run the  command: `composer fix`. And send again.

**Comment by shishamchudal** [comment]
composer fix
> ./vendor/bin/php-cs-fixer fix
sh: ./vendor/bin/php-cs-fixer: No such file or directory
Script ./vendor/bin/php-cs-fixer fix handling the fix event returned with error code 127

**Comment by dansysanalyst** [comment]
Hi @shishamchudal,

- run
composer install

- fix code styles
composer fix

- run tests
composer test

- run static analysis
composer test:types

**Comment by shishamchudal** [comment]
Hopefully, the commit should fix it. 😬

**Comment by luanfreitasdev** [comment]
Thanks @shishamchudal

**Pull request merged**
