### PR TITLE
Persist livewire data (restore after refresh page).

### PR DESCRIPTION
**Pull request by jamesRUS52**
Saving columns visibility and filters to local storage.

### CODE REVIEW

**Comment by luanfreitasdev** [comment]
Can you talk about what behavior this changes?

**Comment by jamesRUS52** [comment]
when
persistFiltersAndColumns() enabled 
```
    public function setUp(): void
    {
        $this->showCheckBox()
            ->showPerPage()
            ->showExportOption('download', ['excel', 'csv'])
            ->showSearchInput()
            ->showToggleColumns()
            ->persistFiltersAndColumns()
        ;
        
    }
```
columns and filters saves to local storage.
User can configure table (set filters and visibility columns) and this settings will be restored from local storage when he open this page in next time

**Comment by luanfreitasdev** [comment]
I tried here and still don't understand. Can you send a video (no audio anyway) demonstrating the functionality?

**Comment by jamesRUS52** [comment]
[video example](https://vimeo.com/user167304301/review/679537042/5454f0a49a)

input filter
hide the column
refresh page
input filter and hidden column in last state (inputed and hidden)

**Comment by luanfreitasdev** [comment]
Invalid link

**Comment by jamesRUS52** [comment]
[video](https://vimeo.com/679537042)

**Comment by dansysanalyst** [comment]
Hello @jamesRUS52,

Thanks for the contribution, *a priori* I think this is a very interesting idea!

Perhaps `->persists()` would be a better name than `->persistFiltersAndColumns()`.

Currently, we would be persisting Filters and Column, but this would leave a possibility open to customize the persist function or even add a 

``` php
 $this->showCheckBox()
         ->persists([
                   'columns'     => true,
                   'filters'     => false,
                   'can'        =>  auth()->is_admin
               ]);
```

Is there a need to control persistence by events? For instance, another component wants to deactivate the persistence.

**Comment by jamesRUS52** [comment]
I'l take a pause to analyze. 
Now I think using cookies is better way instead of local storage to avoid additional livewire request and default table render at mount.
Yes, I'l rename the method to separate control of columns and filters.

**Comment by jamesRUS52** [comment]
->persist(['columns','filters']);

**Comment by luanfreitasdev** [comment]
Great job, I'm merging into the _dev_ branch.

However, there are a few things missing to launch:

- [x]   Fix the multi select tailwind state (I already did that)
- [ ]   Fix multi select state for bootstrap 5
- [ ]   Do some tests

**Comment by jamesRUS52** [comment]
> * [ ]    Fix multi select state for bootstrap 5

If you have any error with multi select on this branch, I think it should be resoleved by [294](https://github.com/Power-Components/livewire-powergrid/pull/294).
I checked, multiselect work well on it

or show me what is wrong?

**Comment by luanfreitasdev** [comment]
I think I have this problem, if I put hidden in some column along with ->persist(['columns', 'filters']) the column is still displayed on the screen

image

image

image

**Comment by jamesRUS52** [comment]
I think hidden() was added after cookie already have non hidden state.
I added additional condition to restore hidden state.
Now it will be restored only if column has forseHidden = false (see #307)
Now if end user has cookie with visible column and after that developer change column configuration to hidden(), the column state will not be restored and column will be not visible.
I think it will be OK

**Pull request merged**
