### PR TITLE
🌐 CA|ES|DE Filter translation + Badge for tests + PhpStorm

### PR DESCRIPTION
**Pull request by dansysanalyst**
Hi Luan,

I sent some of the missing labels for the filter select and a test badge:

Screenshot 2021-11-28 at 11 44 19

I also suggest a PhpStorm thank you notice.

### CODE REVIEW

**Review by stifamajstor — CHANGES_REQUESTED** [review]
In the german file, 'is_empty' and 'is_not_empty' should be reversed because 'ausgefüllt' means 'is_not_empty'.

**Comment by dansysanalyst** [comment]
> In the german file, 'is_empty' and 'is_not_empty' should be reversed because 'ausgefüllt' means 'is_not_empty'.

Thank you so much for pointing it out @stifamajstor!
You are absolutely right!

**Comment by dansysanalyst** [comment]
@stifamajstor : Would you be interested in sending a PR for Croatian language? This would be really cool! 🙂

**Comment by stifamajstor** [comment]
Sure @dansysanalyst . Would be happy to help,

**Pull request merged**
