### PR TITLE
Conditional column hide

### PR DESCRIPTION
**Pull request by pauleniz**
I think this will be useful since sometimes column needs to be hidden on condition. 

P. S. First time doing a pull request not sure if I did it correctly.

### CODE REVIEW

**Comment by pauleniz** [comment]
I don't know where to run the commands composer fix and composer check

**Comment by dansysanalyst** [comment]
@pauleniz  No problem, here is what you need to do:

Open your terminal, the same way you would normally do when you want to execute `composer install xyz`.

Navigate to the PowerGrid source folder and run the commands:

CleanShot 2022-01-31 at 12 19 21@2x

First:

`composer install`

(it will install all dependencies)

Then:

`composer fix` 

Finally:

`composer check`

If there are no errors, you will see something like:

CleanShot 2022-01-31 at 12 22 19@2x

**Comment by pauleniz** [comment]
Ok I cloned the repo to my Github desktop then I ran composer install, then composer fix, then composer check. And I got this:
image
I guess its because I'm using PHP 7.3? I would really like to learn how to do this since I use this package a lot.

**Comment by dansysanalyst** [comment]
@pauleniz You did nothing wrong.

The `composer check` is currently only running in Linux. I will see how to fix that.

For the moment,  please run

`composer fix`

then

`test:types`

and finally

`composer test:sqlite`


--

`composer:check` is just a group of commands, and of them is not working on windows.

Thanks for your help and commitment.

**Comment by pauleniz** [comment]
Sorry, I feel like a total noob. Half of test fail because of NumberFormatter class
image
I feel like I'm just wasting your time Dan... I read Contributing.md and failed to complete that...

**Comment by dansysanalyst** [comment]
There is no such a thing as `noob`, we are all learning something new every day. 

A wild guess: Do you have extension=ext/php_intl.dll enabled?

It's been years since I last used xaamp, but I think it is something like n `c:\xaamp\php\php.ini` and then you uncomment `;extension=php_intl.dll` ===> `extension=php_intl.dll`.

**Comment by dansysanalyst** [comment]
@pauleniz you problably need to restart apache after the change!

**Comment by pauleniz** [comment]
Yes it fixed the problem but 24 skipped:
image
image

**Comment by dansysanalyst** [comment]
I haven't seen this one before.

@luanfreitasdev Do you see why would it conflict?

@pauleniz on your last commit, the problem was with the cs-fixer, so `composer fix` and a new commit of the fixed file should solve it and I think it would pass on the github action checks.

**Comment by dansysanalyst** [comment]
Congratulations @pauleniz, all checks have passed! Good work!

Let's wait for @luanfreitasdev review.

**Comment by pauleniz** [comment]
Thank you for your help Dan!

**Comment by mateusjatenee** [comment]
Cool stuff. Congrats on the first PR @pauleniz

**Comment by luanfreitasdev** [comment]
Hi @pauleniz , thank you very much for your PR

**Pull request merged**
