### PR TITLE
[5x] Fix crashed table

### PR DESCRIPTION
**Pull request by CrazyBoy49z**
## ⚡ PowerGrid - Pull Request

Welcome and thank you for your interest in contributing to our project!. You must use this template to submit a Pull Request or it will not be accepted.

--- 
#### Motivation

- [x] Bug fix
- [ ] Enhancement
- [ ] New feature
- [ ] Breaking change

#### Description

This Pull Request adds...

#### Documentation

 This PR requires [Documentation](https://github.com/Power-Components/powergrid-doc) update?

- [ ] Yes
- [x] No
- [ ] I have already submitted a Documentation pull request.

### CODE REVIEW

**Comment by CrazyBoy49z** [comment]
image

`Column::action(__('Action')),`


```
public function actions(Blog $row): array
    {
        return [
            Button::make('show-on-site', '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
             class="feather feather-external-link text-white">
            <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
            <polyline points="15 3 21 3 21 9"></polyline>
            <line x1="10" y1="14" x2="21" y2="3"></line>
        </svg>')
                ->target('_blank')
                ->class('btn btn-sm btn-primary')
                ->route('admin.blog.show-on-site', ['blog' => $row->id]),
            Button::make('show', '<svg xmlns="http://www.w3.org/2000/svg"  width="24" height="24" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
  <path d="M12 15a3 3 0 100-6 3 3 0 000 6z"></path>
  <path fill-rule="evenodd" d="M1.323 11.447C2.811 6.976 7.028 3.75 12.001 3.75c4.97 0 9.185 3.223 10.675 7.69.12.362.12.752 0 1.113-1.487 4.471-5.705 7.697-10.677 7.697-4.97 0-9.186-3.223-10.675-7.69a1.762 1.762 0 010-1.113zM17.25 12a5.25 5.25 0 11-10.5 0 5.25 5.25 0 0110.5 0z" clip-rule="evenodd"></path>
</svg>')
                ->target('')
                ->class('btn btn-sm btn-secondary')
                ->route('admin.blog.show', ['blog' => $row->id]),
            Button::make('edit', '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
             class="feather feather-edit text-yellow">
            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
            <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
        </svg>')
                ->target('')
                ->class('btn btn-sm btn-warning')
                ->route('admin.blog.edit', ['blog' => $row->id]),

            Button::make('destroy', '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2 text-red">
            <polyline points="3 6 5 6 21 6"></polyline>
            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
            <line x1="10" y1="11" x2="10" y2="17"></line>
            <line x1="14" y1="11" x2="14" y2="17"></line>
        </svg>')
                ->class('btn btn-sm btn-error')
                ->route('admin.blog.destroy', ['blog' => $row->id])
                ->method('delete'),
        ];
    }
```

```
<div class="flex gap-2 w-full">
            

                                                <div wire:key="action-226-render-action.0.show-on-site">
                        <button href="https://finiv.test/uk/admin/blog/showOnSite/226" class="btn btn-sm btn-primary" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-external-link text-white">
            <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
            <polyline points="15 3 21 3 21 9"></polyline>
            <line x1="10" y1="14" x2="21" y2="3"></line>
        </svg></button>
                    </div>
                                    <div wire:key="action-226-render-action.1.show">
                        <button href="https://finiv.test/uk/admin/blog/226" class="btn btn-sm btn-secondary" target=""><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
  <path d="M12 15a3 3 0 100-6 3 3 0 000 6z"></path>
  <path fill-rule="evenodd" d="M1.323 11.447C2.811 6.976 7.028 3.75 12.001 3.75c4.97 0 9.185 3.223 10.675 7.69.12.362.12.752 0 1.113-1.487 4.471-5.705 7.697-10.677 7.697-4.97 0-9.186-3.223-10.675-7.69a1.762 1.762 0 010-1.113zM17.25 12a5.25 5.25 0 11-10.5 0 5.25 5.25 0 0110.5 0z" clip-rule="evenodd"></path>
</svg></button>
                    </div>
                                    <div wire:key="action-226-render-action.2.edit">
                        <button href="https://finiv.test/uk/admin/blog/226/edit" class="btn btn-sm btn-warning" target=""><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit text-yellow">
            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
            <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
        </svg></button>
                    </div>
                                    <div wire:key="action-226-render-action.3.destroy">
                        <form target="_self" action="https://finiv.test/uk/admin/blog/226" method="post">
    @method('delete')
    @csrf
    <button type="submit" class="btn btn-sm btn-error" id=""><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2 text-red">
            <polyline points="3 6 5 6 21 6"></polyline>
            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
            <line x1="10" y1="11" x2="10" y2="17"></line>
            <line x1="14" y1="11" x2="14" y2="17"></line>
        </svg></button>
</form>
                    </div>
                 
             
        </div>
```


` Column::make(__('Action'), 'actions'),` return array

**Comment by luanfreitasdev** [comment]
@CrazyBoy49z , can you check again, please ?
Thanks

**Comment by CrazyBoy49z** [comment]
> @CrazyBoy49z , can you check again, please ? Thanks

It works, but I can't test the delete button yet

The delete button has no confirmation

**Comment by CrazyBoy49z** [comment]
image

**Comment by luanfreitasdev** [comment]
I didn't understand. It's rendering correctly, right?

**Comment by CrazyBoy49z** [comment]
> I didn't understand. It's rendering correctly, right?

```
<div wire:key="action-225-render-action.3.destroy">
                        <form target="_self" action="https://finiv.test/uk/admin/blog/225" method="post">
    <input type="hidden" name="_method" value="delete">    <input type="hidden" name="_token" value="9YHxow4JmFmvf7Vvhe024Y4nj9lcbJsEyYHDZiDq">    <button type="submit" class="btn btn-sm btn-error" id=""><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2 text-red">
            <polyline points="3 6 5 6 21 6"></polyline>
            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
            <line x1="10" y1="11" x2="10" y2="17"></line>
            <line x1="14" y1="11" x2="14" y2="17"></line>
        </svg></button>
</form>
                    </div>
```

**Comment by CrazyBoy49z** [comment]
> I didn't understand. It's rendering correctly, right?

If you're talking about a method, yes he rendered correctly

**Pull request merged**
