### PR TITLE
Enhancement/disable rule select all value

### PR DESCRIPTION
**Pull request by abhaypithadiya**
## ⚡ PowerGrid - Pull Request

Welcome and thank you for your interest in contributing to our project!. You must use this template to submit a Pull Request or it will not be accepted.

--- 
#### Motivation

- [x] Bug fix
- [x] Enhancement
- [ ] New feature
- [ ] Breaking change

#### Description

This Pull Request adds enhancement to the select all feature. If the checkbox rule is disabled, the value should not be selected when clicking on select all checkbox.

#### Documentation

 This PR requires [Documentation](https://github.com/Power-Components/powergrid-doc) update?

- [ ] Yes
- [X] No
- [ ] I have already submitted a Documentation pull request.

### CODE REVIEW

**Comment by abhaypithadiya** [comment]
Hey @luanfreitasdev! Can you please help me out with this?

**Comment by luanfreitasdev** [comment]
I think we shouldn't change the behavior of the checkbox because there is a "disable" action on some button. To do this, use Rule::checkbox to apply a rule

```php
Rule::checkbox()
     ->when(fn ($dish) => $dish->id == 8)
     ->hide(),
```

**Comment by abhaypithadiya** [comment]
True, but what if while using bulk delete you don't want the user to select the checkbox for that row. Because if we hide the checkboxes it looks odd and we might need to give clarification on why few rows have checkboxes and why others don't. Even if the rows are disabled the checkbox value gets selected. But I am okay if we don't add this change. 😅😁

**Comment by luanfreitasdev** [comment]
I don't think I entirely understand what behavior you expect. Can you send part of a screenshot describing the problem?

**Comment by abhaypithadiya** [comment]
https://github.com/Power-Components/livewire-powergrid/assets/107384999/6b591328-58d5-478f-9586-4f2bcb79920b

In the attached video, there are only three checkboxes which are not disabled and others are disabled, disabled checkboxes can not be selected individually hence there values are not stored. But when you click on select all button all of the checkboxes values are stored even the checkboxes which are disabled which shouldn't be the case as they are disabled.

**Comment by luanfreitasdev** [comment]
Right. In this case, it makes sense

**Comment by abhaypithadiya** [comment]
Yess. Sorry for the misunderstanding 😅

**Pull request merged**
