### PR TITLE
Support for models with different database connection property

### PR DESCRIPTION
**Pull request by eafarooqi**
## ⚡ PowerGrid - Pull Request

Welcome and thank you for your interest in contributing to our project!. You must use this template to submit a Pull Request or it will not be accepted.

--- 
#### Motivation

- [ ] Bug fix
- [X] Enhancement
- [ ] New feature
- [ ] Breaking change

#### Description

This pull request add the support for the models which have a connection property defined which is different from the default one. 

Issue:
When models haves database connection property defined which is different from the default one, then the global search doesn't work as the getColumnList() function was using the default database connection.

#### Documentation

 This PR requires [Documentation](https://github.com/Power-Components/powergrid-doc) update?

- [ ] Yes
- [X] No
- [ ] I have already submitted a Documentation pull request.

### CODE REVIEW

**Comment by luanfreitasdev** [comment]
Thank you @eafarooqi for this PR! Can you fix the phpstan warning?

**Comment by dansysanalyst** [comment]
I am not sure if one can alter the connection on an instantiated `Query Builder`, as it contains the injected dependency to `ConnectionInterface`.

Perhaps the logic should be moved into a `resolveConnection()` method. This could early return `Schema::getColumns($modelTable)` when dealing with a Query Builder, or resolve the connection when dealing with `EloquentBuilder`.

**Review by dansysanalyst — CHANGES_REQUESTED** [review]
Please do not ignore the error. Fix it instead.

**Comment by eafarooqi** [comment]
@dansysanalyst 
on QueryBuilder ->getConfig('driver') or ->getConfig('name') will fail with phpstan and has to be ignored as already done at `src/DataSource/Support/Sql.php:20`

**Comment by dansysanalyst** [comment]
> @dansysanalyst on QueryBuilder ->getConfig('driver') or ->getConfig('name') will fail with phpstan and has to be ignored as already done at `src/DataSource/Support/Sql.php:20`

LGTM 👍

**Pull request merged**
