### PR TITLE
Add missing quote in dispatchTo rule

### PR DESCRIPTION
**Pull request by tompin82**
## ⚡ PowerGrid - Pull Request

Welcome and thank you for your interest in contributing to our project!. You must use this template to submit a Pull Request or it will not be accepted.

--- 
#### Motivation

- [x] Bug fix
- [ ] Enhancement
- [ ] New feature
- [ ] Breaking change

#### Description

This Pull Request adds a missing opening quote in the DispatchToRule class. Without this quote, the dispatchTo() wire:click attribute is incorrectly formatted (the event name is not a string) and does not work.

#### Documentation

 This PR requires [Documentation](https://github.com/Power-Components/powergrid-doc) update?

- [ ] Yes
- [x] No
- [ ] I have already submitted a Documentation pull request.

### CODE REVIEW

**Comment by tompin82** [comment]
It would be great if this could be backported to 5.x as well.

Thanks.

**Comment by shazrah** [comment]
Ran into this bug as well, great to see a fix! :)

**Comment by Purpl3ttuce** [comment]
Looks great, this would indeed be beneficial

**Comment by luanfreitasdev** [comment]
Thank you!

**Pull request merged**
