### PR TITLE
Add 'Filtered' label to Export options

### LINKED ISSUE #1043: [Bug]: Export does not honor filtered results in table
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.5

### PowerGrid

4.8.1

### Laravel

10.14.1

### Livewire

2.12.3

### Alpine JS

3.12.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

I have an exchange rates table that holds amounts for two different currencies and I filtered the table by one of them. I exported the results to XLSX and expected that the filters would be honored and the resulting Excel file would only contain entries for that currency, but every entry (for both currencies) was exported.

### To Reproduce...

1. Have an exportable populated powergrid table.
2. Apply a filter to it.
3. Export to Excel XLSX file.

### Extra information

I have done some debugging and pinpointed the issue to this line of code: https://github.com/Power-Components/livewire-powergrid/blob/5faeb879af0d31e1d72bd38083d328791ea53ad3/src/Traits/WithExport.php#L180

If I place the following code before that line I can see that the `$processDataSource` paginator instance contains only the filtered values (this would be expected):
 
dd($processDataSource->get()->getCollection()->toArray());
 

Running https://github.com/Power-Components/livewire-powergrid/blob/5faeb879af0d31e1d72bd38083d328791ea53ad3/src/Traits/WithExport.php#L180, specifically `$processDataSource->prepareDataSource()` yields the following error:
`Typed property PowerComponents\LivewirePowerGrid\PowerGridComponent::$datasource must not be accessed before initialization` (I get this error because I placed the command `dd($this->component->datasource);` at the start of the function in line https://github.com/Power-Components/livewire-powergrid/blob/5faeb879af0d31e1d72bd38083d328791ea53ad3/src/ProcessDataSource.php#L51) but it exposes the issue that the datastore contains no value and hence it is being initialized with a "default query".

This is the query that the Paginator executes: ``"select * from `exchange_rates` where ((`currency` = ?) and (`date` between ? and ?))"`` versus the query that the actual results export executes: ``"select * from `exchange_rates`"``.

Is there a datasource assignment missing to use the one that's coming from the filtered component?

### PR DESCRIPTION
**Pull request by d4rkstar**
## ⚡ PowerGrid - Pull Request

Welcome and thank you for your interest in contributing to our project!. You must use this template to submit a Pull Request or it will not be accepted.

--- 
#### Motivation

- [X] Bug fix
- [X] Enhancement
- [ ] New feature
- [ ] Breaking change

#### Description

This Pull Request starts from Fix #1043: Export does not honor filtered results in table #1044.
I've added also a small visual improvements: the dropdown menu will show if export is for filtered results or all/selected results

#### Documentation

 This PR requires [Documentation](https://github.com/Power-Components/powergrid-doc) update?

- [ ] Yes
- [X] No
- [ ] I have already submitted a Documentation pull request.

### CODE REVIEW

**Comment by d4rkstar** [comment]
@luanfreitasdev :sunglasses:

**Comment by luanfreitasdev** [comment]
Thanks, it has some bugs, but the job is good.

- It is showing duplicates;
- When I select it, the export still has some bugs in the lines

image

**Comment by d4rkstar** [comment]
> Thanks, it has some bugs, but the job is good.
> 
> * It is showing duplicates;
> * When I select it, the export still has some bugs in the lines
> 
> image

Uhm.. let me check better...

**Comment by d4rkstar** [comment]
Hello,
did a test with the powergrid-demo and all seems to be fine here:

image

As you can see in the image, the labels are not duplicated (was my mistake).
I've filtered the grid and then done two exports:
- filtered 
- selected

You can see the content inside the two Excel files. I found no issues with extra rows in excel files.

Let me know if this is ok on your side.

Bruno

**Comment by d4rkstar** [comment]
Hello @luanfreitasdev did you had some time to check?

**Comment by luanfreitasdev** [comment]
> Hello @luanfreitasdev did you had some time to check?

Yes!. Thank you

**Pull request merged**
