### PR TITLE
fix

### PR DESCRIPTION
**Pull request by racerguy**
## ⚡ PowerGrid - Pull Request

Welcome and thank you for your interest in contributing to our project!. You must use this template to submit a Pull Request or it will not be accepted.

--- 
#### Motivation

- [ x] Bug fix
- [ ] Enhancement
- [ ] New feature
- [ ] Breaking change

#### Description

This Pull Request adds...

#### Documentation

 This PR requires [Documentation](https://github.com/Power-Components/powergrid-doc) update?

- [ ] Yes
- [x ] No
- [ ] I have already submitted a Documentation pull request.

### CODE REVIEW

**Comment by luanfreitasdev** [comment]
Hello!. I can't reproduce the problem, can you record a video?

**Comment by racerguy** [comment]
> Hello!. I can't reproduce the problem, can you record a video?
@luanfreitasdev  Is there a way I can send you it privately because of the data?

**Comment by luanfreitasdev** [comment]
Can you send it to me by email, please?

luanfreitas10@protonmail.com

**Comment by racerguy** [comment]
> Can you send it to me by email, please?
> 
> [luanfreitas10@protonmail.com](mailto:luanfreitas10@protonmail.com)

@luanfreitasdev sent

**Pull request merged**
