### PR TITLE
fix toggle script errors

### PR DESCRIPTION
**Pull request by CrazyBoy49z**

### CODE REVIEW

**Comment by luanfreitasdev** [comment]
What error is he fixing? if you can describe it better, as simple as it is because it seems to be passing an int value. hear any case of being string ?

image

**Comment by CrazyBoy49z** [comment]
image

**Comment by CrazyBoy49z** [comment]
tailwind

https://github.com/Power-Components/livewire-powergrid/blob/main/resources/views/components/frameworks/tailwind/toggleable.blade.php#L11 

bootstrap5
https://github.com/Power-Components/livewire-powergrid/blob/main/resources/views/components/frameworks/bootstrap5/toggleable.blade.php#L5


image

image

**Comment by luanfreitasdev** [comment]
Yes, it turned out similar and apparently fixes a hidden issue. In that case tailwind would also be passing a wrong value. Should we really convert null to int ? or disable the toggle?

**Comment by CrazyBoy49z** [comment]
> As it wasn't able to get the value there in the $column->field, the action shouldn't even work. And if we disable in this case there is no value?

This is an artifact php with js 

false
```
@php 
   $bool = false;
@php 

js 
this is {{ $bool }} 

// render js 

this is 
```

true
```
@php 
   $bool = true;
@php 

js 
this is {{ $bool }} 

// render js  

this is true
```

**Comment by luanfreitasdev** [comment]
makes sense 🤔

**Comment by CrazyBoy49z** [comment]
> makes sense 🤔

Similar problem

https://github.com/modxcms/revolution/pull/14535

**Comment by luanfreitasdev** [comment]
Thanks

**Pull request merged**
