### PR TITLE
Fixed issues with pagination responsiveness on mobile

### PR DESCRIPTION
**Pull request by Stridesdata**
Fixed issues with pagination responsiveness on mobile- bootstrap5 theme. Pagination no longer extends from card on mobile

### CODE REVIEW

**Comment by luanfreitasdev** [comment]
Hi, thank you so much for submitting your PR!

We have 2 problems that we need to find a way through,

1st - when the user selects the showRecourdCount option the mobile is still breaking (this was fixed yesterday).
_current:_
image
_now:_
image


2nd - when I'm on big screen the layout is getting lost
_current:_
image

now:
image

If you can resend it, I will review it again so we can continue with this correction.

Thanks

**Review by luanfreitasdev — CHANGES_REQUESTED** [review]
Hi, thank you so much for submitting your PR!

We have 2 problems that we need to find a way through,

**Comment by Stridesdata** [comment]
Okay fixing

**Comment by Stridesdata** [comment]
I have edited to fix those issues raised. Hope it meets your requirements

**Comment by luanfreitasdev** [comment]
it hasn't all been centered yet because of the pagination

image

Maybe it would be an exit to leave all items on the left except the pagination?

**Pull request merged**
