### PR TITLE
[4x] Feature/Dynamic Filter

### PR DESCRIPTION
**Pull request by luanfreitasdev**
This PR adds the possibility for us to replace some filtering components with other external components.

An example of practical use is the use of **x-select async ([wireui](https://github.com/wireui/wireui))** which is very good in all cases, especially when we have a lot of data and we don't want to load everything immediately:

Learn more about this at: https://livewire-wireui.com/docs/select#async-search

### How to call:

1.   param: filter - type of filter powergrid needs to process internally in the call
2.   param: data_field - field name in database table
3.   param: component - component name, ex: x-select = select, x-input = input
4.   param: attributes - attributes that will be dynamically sent to the component

### Multi Select
```php
->makeDynamicInput(DynamicInput::FILTER_MULTI_SELECT, 'category_id', 'select', [
       'class'        => 'min-w-[170px]',
       'async-data'   => route('categories.index'),
       'option-label' => 'name',
       'multiselect'  => true,
       'option-value' => 'id',
       'placeholder'  => 'Placeholder',
]),
```
image

### Boolean
```php
->makeDynamicInput(DynamicInput::FILTER_BOOLEAN, 'in_stock', 'select', [
       'class'   => 'min-w-[170px]',
       'options' => [
            ['name' => 'Active',  'value' => true],
            ['name' => 'Inactive', 'value' => false],
       ],
       'option-label' => 'name',
       'option-value' => 'value',
       'placeholder'  => 'Choose',
])
```

image

### Input Contains

```php
->makeDynamicInput(DynamicInput::FILTER_INPUT_TEXT_CONTAINS, 'chef_name', 'input', [
       'class'       => 'min-w-[170px]',
       'placeholder' => 'Search',
])
```

image

### CODE REVIEW

**Comment by akulmehta** [comment]
@luanfreitasdev I think the video cannot be viewed.

**Comment by luanfreitasdev** [comment]
I didn't understand

**Comment by luanfreitasdev** [comment]
I had made a demo. But there are still tests to do

**Comment by akulmehta** [comment]
> I didn't understand

Nevermind it is working now.

**Pull request merged**
