### PR TITLE
Removed semicolon causing error in stub

### PR DESCRIPTION
**Pull request by akulmehta**
# ⚡ PowerGrid ⚡ Pull Request

Welcome and thank you for your interest in contributing to our project!. You must use this template to submit a Pull Request or it will not be accepted.

💡 Please complete this template to submit a Pull Request, we cannot accept incomplete Pull Requests.

## Guidelines

`   🗒️ `  Please read the [Contributing Guide](https://github.com/Power-Components/livewire-powergrid/blob/main/CONTRIBUTING.md) and follow all steps listed there.

`   ✍️ `  Give this PR a meaningful title.

`   📣 `  Describe your PR details below.

### Motivation

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change

### Related Issue(s)

None

### Description

The last update to stubs had a semicolon which was causing an error when producing a new table. Just removed it.

### Contribution Guide

- [x] I have read and followed the steps listed in the [Contributing Guide](https://github.com/Power-Components/livewire-powergrid/blob/main/CONTRIBUTING.md).

### Documentation

 This PR requires [Documentation](https://github.com/Power-Components/powergrid-doc) update?

- [ ] Yes
- [x] No
- [ ] I have already submitted a Documentation pull request.

### CODE REVIEW

**Comment by akulmehta** [comment]
hmmm why is the test failing? @dansysanalyst please help.

**Comment by dansysanalyst** [comment]
CC @luanfreitasdev 

Good eye @akulmehta! Thank you so much for this one.

I am out of town this weekend but on a quick look I might have spotted a problem:

Dish seeder `produced_at` is out of our control:

```
 $dish['produced_at'] =  $faker->dateTimeBetween($startDate = '-1 months', $endDate = 'now')->format('Y-m-d');
```

The `SearchableRawTest`, looks for dishes in `09/09/2022` which didn't exist before and will not exist in the future, but exists now because we are in 09/2022.

```php
it('searches data using whereRaw on sqlite', function (string $component, object $params) {
    livewire($component, ['database' => 'sqlite'])
        ->call($params->theme)
        ->set('search', '09/09/2021')
        ->assertSee('Polpetone Filé Mignon')
        ->assertDontSee('Barco-Sushi Simples')
        ->assertDontSee('No records found')
        # 09/09/2022
        ->set('search', '09/09/2022') //Before
        ->set('search', '09/09/2046') //Changed to
        ->assertSee('No records found')
        # 06/2026
        ->set('search', '06/2026')
        ->assertSee('Francesinha')
        ->assertDontSee('Polpetone Filé Mignon');
})->with('searchable-raw')->requiresSQLite();
```

I think it would be safer to set a date range for production in the year 2021. Under control.

(still checking this situation)

**Comment by dansysanalyst** [comment]
@luanfreitasdev 

I suggest modifying `tests/Actions/TestDatabase.php` to generate dates in 2021 and specific dishes used in tests continue having hard coded dates.

```php
if (!isset($dish['produced_at'])) {
    $dish['produced_at'] = $faker->dateTimeBetween($startDate = '2021-01-01', $endDate = '2021-12-31')->format('Y-m-d');
}
```

**Comment by luanfreitasdev** [comment]
Thank you @akulmehta ,

@dansysanalyst , your solution is the only one at the moment. By the way, this showed that the filter really works.

Thank you all

**Pull request merged**
